spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/evac_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:aayush}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.sql.init.mode=never

server.port=${PORT:8080}
